name: Nodejs CI
on:
  push:
    branches:
      - master
# on: push
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
      fail-fast:
        false
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: test leetcode
      run: cd leetcode && yarn --frozen-lockfile && yarn run test

    - name: build blogs
      run: cd blogs && yarn --frozen-lockfile && yarn run build && yarn run deploy:ci
      env:
        GITHUB_PAT: ${{ secrets.GitHub_PAT }}
        demo: test
